# -*- coding: utf-8 -*-
"""Pythonbasics4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_XFnvYGZ3m3honnZSlOtKdxAoNa07j2w
"""

def apply_discount(price,discount):
    final_price = price - (discount/100*price)
    print(final_price)
    if not isinstance(price,(int,float)):
        print('The price should be a number')
    if not isinstance(discount,(int,float)):
        print('The discount should be a number')
    if(price<=0):
        print('The price should be greater than 0')
    if (discount<=0 or discount>=100):
        print('The discount should be between 0 and 100')



apply_discount(100, 20)
apply_discount(200, 50)
apply_discount(50, 0)
apply_discount(50,100)
apply_discount(74.5, 20.0)